<?php
/**
 * Google OAuth Configuration
 * 
 * SECURITY: For production, use environment variables instead of hardcoded values.
 * Example: getenv('GOOGLE_CLIENT_ID') ?: 'default_value'
 * 
 * @package Config
 */

// Use environment variables if available, otherwise fall back to hardcoded values
// In production, set these via .env file or server environment variables
return [
    'client_id' => getenv('GOOGLE_CLIENT_ID') ?: '370401276357-ig4qqi7660f3934gagpt2pavosnhceuj.apps.googleusercontent.com',
    'client_secret' => getenv('GOOGLE_CLIENT_SECRET') ?: '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',
    // Note: redirect_uri is dynamically generated by the code, but listed here for reference
    // Make sure both URIs below are added in Google Cloud Console -> Credentials -> Authorized redirect URIs
    'redirect_uris' => [
        'http://localhost/system/students/google_callback.php',
        'https://subcallosal-lilian-unconsecutively.ngrok-free.dev/system/students/google_callback.php'
    ],
    'scopes' => [
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile'
    ]
];
