<?php


return [
    'client_id' => '370401276357-ig4qqi7660f3934gagpt2pavosnhceuj.apps.googleusercontent.com',
    'client_secret' => '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',
    // Note: redirect_uri is dynamically generated by the code, but listed here for reference
    // Make sure both URIs below are added in Google Cloud Console -> Credentials -> Authorized redirect URIs
    'redirect_uris' => [
        'http://localhost/system/students/google_callback.php',
        'https://subcallosal-lilian-unconsecutively.ngrok-free.dev/system/students/google_callback.php'
    ],
    'scopes' => [
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile'
    ]
];
