const testCases = [
  {
    "id": "TC-001",
    "module": "Applicant Registration",
    "scenario": "New applicant registration",
    "preconditions": "User is on registration page",
    "steps": "Fill in all fields and click 'Register'",
    "data": "First Name, Last Name, Email, Applicant Type",
    "expected": "Account created, credentials sent via email",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-002",
    "module": "Applicant Registration",
    "scenario": "Registration with missing fields",
    "preconditions": "User is on registration page",
    "steps": "Leave one field blank and click submit",
    "data": "Missing Email",
    "expected": "Error message displayed, no account created",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-003",
    "module": "Applicant Registration",
    "scenario": "Duplicate email registration",
    "preconditions": "Email already exists",
    "steps": "Enter the same email again",
    "data": "Existing Email",
    "expected": "System displays 'Email already registered' message",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-004",
    "module": "Applicant Registration",
    "scenario": "Invalid email format",
    "preconditions": "User is on registration page",
    "steps": "Enter incorrect email format and click Register",
    "data": "ash123@",
    "expected": "System displays 'Invalid email format'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-005",
    "module": "Applicant Registration",
    "scenario": "Registration with all valid inputs",
    "preconditions": "System is online",
    "steps": "Enter valid applicant details",
    "data": "Complete user info",
    "expected": "Registration successful, confirmation email sent",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-006",
    "module": "Log In",
    "scenario": "Successful login",
    "preconditions": "Registered account exists",
    "steps": "Enter valid email and password, click Login",
    "data": "Valid credentials",
    "expected": "Redirected to dashboard",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-007",
    "module": "Log In",
    "scenario": "Login with wrong password",
    "preconditions": "User account exists",
    "steps": "Enter valid email, wrong password",
    "data": "Invalid password",
    "expected": "Error 'Incorrect password' shown",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-008",
    "module": "Log In",
    "scenario": "Login with unregistered email",
    "preconditions": "User not yet registered",
    "steps": "Enter unregistered email",
    "data": "unknown@email.com",
    "expected": "Error 'Account not found' displayed",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-009",
    "module": "Log In",
    "scenario": "Empty login fields",
    "preconditions": "Login page open",
    "steps": "Click Login without entering credentials",
    "data": "Blank fields",
    "expected": "System prompts user to fill required fields",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-010",
    "module": "Log In",
    "scenario": "Password visibility toggle",
    "preconditions": "Login page open",
    "steps": "Click eye icon on password field",
    "data": "Password field",
    "expected": "Password becomes visible",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-011",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Step 1 - Personal info save",
    "preconditions": "User logged in",
    "steps": "Fill and click 'Save and Continue'",
    "data": "Personal info fields",
    "expected": "Data saved, proceed to Step 2",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-012",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Step 1 - Missing required fields",
    "preconditions": "User in Step 1",
    "steps": "Leave one field empty and save",
    "data": "Missing last name",
    "expected": "Error 'Required field missing'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-013",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Step 2 - Educational background",
    "preconditions": "User in Step 2",
    "steps": "Enter school info and continue",
    "data": "School, Strand",
    "expected": "Data saved, proceed to Step 3",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-014",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Step 3 - Campus & College selection",
    "preconditions": "User in Step 3",
    "steps": "Select campus and college",
    "data": "Campus photo button, college logo",
    "expected": "Selection saved",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-015",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Step 4 - Document upload validation",
    "preconditions": "User in Step 4",
    "steps": "Upload incomplete files",
    "data": "Missing report card",
    "expected": "System prompts for missing files",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-016",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Step 5 - Review and confirm",
    "preconditions": "User in Step 5",
    "steps": "Click confirm after checking details",
    "data": "Confirmed data",
    "expected": "Profile locked and ready for review",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-017",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Return to previous step",
    "preconditions": "User in Step 3",
    "steps": "Click Back to Step 2",
    "data": "Navigation action",
    "expected": "System returns to Step 2 with saved data",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-018",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Session saving test",
    "preconditions": "Session active",
    "steps": "Logout and log back in",
    "data": "Saved data",
    "expected": "User resumes at last completed step",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-019",
    "module": "Document Upload",
    "scenario": "Upload Grade 11 1st Sem Card",
    "preconditions": "User in Step 4",
    "steps": "Select file and click Upload",
    "data": "Valid PDF file",
    "expected": "File uploaded successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-020",
    "module": "Document Upload",
    "scenario": "Invalid file type upload",
    "preconditions": "User in Step 4",
    "steps": "Try uploading .exe file",
    "data": "file.exe",
    "expected": "Error 'Invalid file format'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-021",
    "module": "Document Upload",
    "scenario": "Upload multiple files",
    "preconditions": "User in Step 4",
    "steps": "Attach multiple files in additional uploads",
    "data": "Multiple PDFs",
    "expected": "All files uploaded",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-022",
    "module": "Document Upload",
    "scenario": "Missing optional file",
    "preconditions": "User in Step 4",
    "steps": "Skip optional file upload",
    "data": "No file for NCII",
    "expected": "System allows continuation",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-023",
    "module": "Exam Management",
    "scenario": "Create new exam version",
    "preconditions": "Admin logged in",
    "steps": "Enter exam details and click Create",
    "data": "Exam Title, Year",
    "expected": "New exam version added",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-024",
    "module": "Exam Management",
    "scenario": "Edit exam questions",
    "preconditions": "Exam version exists",
    "steps": "Modify question and click Save",
    "data": "Updated question text",
    "expected": "Changes saved successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-025",
    "module": "Exam Management",
    "scenario": "Publish exam version",
    "preconditions": "Exam exists",
    "steps": "Select and mark as Published",
    "data": "Exam version 2025",
    "expected": "Exam visible to applicants",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-026",
    "module": "Exam Management",
    "scenario": "Unpublish exam version",
    "preconditions": "Published exam exists",
    "steps": "Click Unpublish",
    "data": "Published exam",
    "expected": "Exam hidden from applicants",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-027",
    "module": "Exam Management",
    "scenario": "Randomize questions",
    "preconditions": "Exam version created",
    "steps": "Enable randomize toggle",
    "data": "Randomize=True",
    "expected": "Exam displays randomized question order",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-028",
    "module": "Entrance Exam",
    "scenario": "Applicant starts exam",
    "preconditions": "Exam published",
    "steps": "Click 'Start Exam'",
    "data": "Exam code 2025",
    "expected": "Exam timer begins",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-029",
    "module": "Entrance Exam",
    "scenario": "Auto-submit after timeout",
    "preconditions": "Timer running",
    "steps": "Let time expire",
    "data": "Time=0",
    "expected": "Exam auto-submitted",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-030",
    "module": "Entrance Exam",
    "scenario": "Manual submission",
    "preconditions": "Exam ongoing",
    "steps": "Click Submit before time ends",
    "data": "Partial answers",
    "expected": "Answers saved, confirmation shown",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-031",
    "module": "Entrance Exam",
    "scenario": "View exam result",
    "preconditions": "Exam completed",
    "steps": "Click View Result",
    "data": "Exam score",
    "expected": "Score displayed correctly",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-032",
    "module": "Interviewer Management",
    "scenario": "Add new interviewer",
    "preconditions": "Chairperson logged in",
    "steps": "Enter name and assign program",
    "data": "Name, Program",
    "expected": "Interviewer added successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-033",
    "module": "Interviewer Management",
    "scenario": "Edit interviewer details",
    "preconditions": "Interviewer exists",
    "steps": "Change info and save",
    "data": "Updated contact",
    "expected": "Changes reflected",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-034",
    "module": "Interviewer Management",
    "scenario": "Delete interviewer",
    "preconditions": "Interviewer record exists",
    "steps": "Click Delete",
    "data": "Interviewer ID",
    "expected": "Record removed from list",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-035",
    "module": "Interviewer Management",
    "scenario": "Duplicate interviewer prevention",
    "preconditions": "Same name exists",
    "steps": "Try adding same interviewer twice",
    "data": "Duplicate entry",
    "expected": "System displays 'Already exists' warning",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-036",
    "module": "Interview Evaluation",
    "scenario": "Start interview evaluation",
    "preconditions": "Applicant assigned",
    "steps": "Open form and input scores",
    "data": "Criteria ratings",
    "expected": "Evaluation saved successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-037",
    "module": "Interview Evaluation",
    "scenario": "Missing evaluation field",
    "preconditions": "Evaluation form open",
    "steps": "Leave one rating blank",
    "data": "Missing score",
    "expected": "System prompts to fill all fields",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-038",
    "module": "Interview Evaluation",
    "scenario": "View evaluation results",
    "preconditions": "Evaluation completed",
    "steps": "Open applicant evaluation record",
    "data": "Applicant ID",
    "expected": "Displays all criteria with scores",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-039",
    "module": "Interview Evaluation",
    "scenario": "Edit submitted evaluation",
    "preconditions": "Evaluation exists",
    "steps": "Click Edit and modify scores",
    "data": "Updated rating",
    "expected": "Changes saved successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-040",
    "module": "Stanine Input",
    "scenario": "Input stanine score",
    "preconditions": "Applicant has exam result",
    "steps": "Admin inputs stanine value",
    "data": "Stanine=7",
    "expected": "Score saved and displayed",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-041",
    "module": "Stanine Input",
    "scenario": "Invalid stanine value",
    "preconditions": "Admin inputting data",
    "steps": "Enter stanine above 9",
    "data": "Stanine=12",
    "expected": "Error 'Invalid range'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-042",
    "module": "Stanine Input",
    "scenario": "Update stanine score",
    "preconditions": "Existing stanine record",
    "steps": "Edit and save new value",
    "data": "Stanine=6",
    "expected": "Record updated successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-043",
    "module": "Stanine Input",
    "scenario": "Auto-calculated eligibility",
    "preconditions": "Stanine entered",
    "steps": "Save record",
    "data": "Stanine=8",
    "expected": "Applicant marked eligible",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-044",
    "module": "Plus Factors",
    "scenario": "Input plus factor based on strand",
    "preconditions": "Applicant SHS info available",
    "steps": "Assign points for strand match",
    "data": "ICT Strand",
    "expected": "Plus points recorded",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-045",
    "module": "Plus Factors",
    "scenario": "Missing strand info",
    "preconditions": "Applicant record incomplete",
    "steps": "Try assigning plus factor",
    "data": "No strand data",
    "expected": "System warns 'No strand info'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-046",
    "module": "Plus Factors",
    "scenario": "Edit plus factor score",
    "preconditions": "Existing record",
    "steps": "Modify plus points",
    "data": "Change +3 to +5",
    "expected": "Value updated successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-047",
    "module": "Reporting",
    "scenario": "Calculate total rating",
    "preconditions": "All scores recorded",
    "steps": "System computes total",
    "data": "Stanine + Interview + Plus",
    "expected": "Final rating displayed accurately",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-048",
    "module": "Reporting",
    "scenario": "Generate applicant list per campus",
    "preconditions": "Admin logged in",
    "steps": "Select campus and click Generate",
    "data": "Talisay Campus",
    "expected": "Report generated",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-049",
    "module": "Reporting",
    "scenario": "Generate list per program",
    "preconditions": "Admin logged in",
    "steps": "Choose BSIS program",
    "data": "BSIS",
    "expected": "Program report shown",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-050",
    "module": "Reporting",
    "scenario": "Export report to PDF",
    "preconditions": "Report generated",
    "steps": "Click Export to PDF",
    "data": "Generated report",
    "expected": "PDF file downloaded",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-051",
    "module": "Reporting",
    "scenario": "Invalid report filter",
    "preconditions": "Admin on report page",
    "steps": "Leave filter blank and click Generate",
    "data": "No selection",
    "expected": "Error 'Please select filter' displayed",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-052",
    "module": "Reporting",
    "scenario": "Generate date range report",
    "preconditions": "Applicants exist",
    "steps": "Select date range and click Generate",
    "data": "01/01\u201301/31",
    "expected": "Displays correct applicants within range",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-053",
    "module": "Reporting",
    "scenario": "Empty result handling",
    "preconditions": "No applicants in range",
    "steps": "Generate report",
    "data": "Invalid date range",
    "expected": "System displays 'No records found'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-054",
    "module": "Session & Account",
    "scenario": "Applicant logs out",
    "preconditions": "User logged in",
    "steps": "Click Logout",
    "data": "Active session",
    "expected": "Redirected to login page",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-055",
    "module": "Session & Account",
    "scenario": "Session timeout",
    "preconditions": "User idle for long period",
    "steps": "Wait for timeout",
    "data": "Inactive session",
    "expected": "System logs out automatically",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-056",
    "module": "Session & Account",
    "scenario": "Change password feature",
    "preconditions": "User logged in",
    "steps": "Go to settings and update password",
    "data": "Old + New password",
    "expected": "Password updated successfully",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-057",
    "module": "Session & Account",
    "scenario": "Forgot password request",
    "preconditions": "User forgot password",
    "steps": "Click 'Forgot Password'",
    "data": "Registered email",
    "expected": "Reset link sent",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-058",
    "module": "Session & Account",
    "scenario": "Admin deletes applicant",
    "preconditions": "Applicant exists",
    "steps": "Click Delete",
    "data": "Applicant ID",
    "expected": "Record removed from database",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-059",
    "module": "Session & Account",
    "scenario": "Chairperson views program applicants",
    "preconditions": "Chairperson logged in",
    "steps": "Open applicant list page",
    "data": "Program=BSIT",
    "expected": "List of BSIT applicants displayed",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-060",
    "module": "Session & Account",
    "scenario": "Final admission approval",
    "preconditions": "Applicant completed all steps",
    "steps": "Chairperson clicks Approve",
    "data": "Eligible applicant",
    "expected": "Admission status changed to 'Accepted'",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-061",
    "module": "Applicant Registration",
    "scenario": "Applicant Registration - Additional validation test 1",
    "preconditions": "Applicant Registration module accessible",
    "steps": "Perform scenario 1 test in applicant registration",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-062",
    "module": "Applicant Registration",
    "scenario": "Applicant Registration - Additional validation test 2",
    "preconditions": "Applicant Registration module accessible",
    "steps": "Perform scenario 2 test in applicant registration",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-063",
    "module": "Applicant Registration",
    "scenario": "Applicant Registration - Additional validation test 3",
    "preconditions": "Applicant Registration module accessible",
    "steps": "Perform scenario 3 test in applicant registration",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-064",
    "module": "Applicant Registration",
    "scenario": "Applicant Registration - Additional validation test 4",
    "preconditions": "Applicant Registration module accessible",
    "steps": "Perform scenario 4 test in applicant registration",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-065",
    "module": "Applicant Registration",
    "scenario": "Applicant Registration - Additional validation test 5",
    "preconditions": "Applicant Registration module accessible",
    "steps": "Perform scenario 5 test in applicant registration",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-066",
    "module": "Log In",
    "scenario": "Log In - Additional validation test 1",
    "preconditions": "Log In module accessible",
    "steps": "Perform scenario 1 test in log in",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-067",
    "module": "Log In",
    "scenario": "Log In - Additional validation test 2",
    "preconditions": "Log In module accessible",
    "steps": "Perform scenario 2 test in log in",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-068",
    "module": "Log In",
    "scenario": "Log In - Additional validation test 3",
    "preconditions": "Log In module accessible",
    "steps": "Perform scenario 3 test in log in",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-069",
    "module": "Log In",
    "scenario": "Log In - Additional validation test 4",
    "preconditions": "Log In module accessible",
    "steps": "Perform scenario 4 test in log in",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-070",
    "module": "Log In",
    "scenario": "Log In - Additional validation test 5",
    "preconditions": "Log In module accessible",
    "steps": "Perform scenario 5 test in log in",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-071",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Applicant Profiling (Steps 1\u20135) - Additional validation test 1",
    "preconditions": "Applicant Profiling (Steps 1\u20135) module accessible",
    "steps": "Perform scenario 1 test in applicant profiling (steps 1\u20135)",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-072",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Applicant Profiling (Steps 1\u20135) - Additional validation test 2",
    "preconditions": "Applicant Profiling (Steps 1\u20135) module accessible",
    "steps": "Perform scenario 2 test in applicant profiling (steps 1\u20135)",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-073",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Applicant Profiling (Steps 1\u20135) - Additional validation test 3",
    "preconditions": "Applicant Profiling (Steps 1\u20135) module accessible",
    "steps": "Perform scenario 3 test in applicant profiling (steps 1\u20135)",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-074",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Applicant Profiling (Steps 1\u20135) - Additional validation test 4",
    "preconditions": "Applicant Profiling (Steps 1\u20135) module accessible",
    "steps": "Perform scenario 4 test in applicant profiling (steps 1\u20135)",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-075",
    "module": "Applicant Profiling (Steps 1\u20135)",
    "scenario": "Applicant Profiling (Steps 1\u20135) - Additional validation test 5",
    "preconditions": "Applicant Profiling (Steps 1\u20135) module accessible",
    "steps": "Perform scenario 5 test in applicant profiling (steps 1\u20135)",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-076",
    "module": "Document Upload",
    "scenario": "Document Upload - Additional validation test 1",
    "preconditions": "Document Upload module accessible",
    "steps": "Perform scenario 1 test in document upload",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-077",
    "module": "Document Upload",
    "scenario": "Document Upload - Additional validation test 2",
    "preconditions": "Document Upload module accessible",
    "steps": "Perform scenario 2 test in document upload",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-078",
    "module": "Document Upload",
    "scenario": "Document Upload - Additional validation test 3",
    "preconditions": "Document Upload module accessible",
    "steps": "Perform scenario 3 test in document upload",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-079",
    "module": "Document Upload",
    "scenario": "Document Upload - Additional validation test 4",
    "preconditions": "Document Upload module accessible",
    "steps": "Perform scenario 4 test in document upload",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-080",
    "module": "Document Upload",
    "scenario": "Document Upload - Additional validation test 5",
    "preconditions": "Document Upload module accessible",
    "steps": "Perform scenario 5 test in document upload",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-081",
    "module": "Exam Management",
    "scenario": "Exam Management - Additional validation test 1",
    "preconditions": "Exam Management module accessible",
    "steps": "Perform scenario 1 test in exam management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-082",
    "module": "Exam Management",
    "scenario": "Exam Management - Additional validation test 2",
    "preconditions": "Exam Management module accessible",
    "steps": "Perform scenario 2 test in exam management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-083",
    "module": "Exam Management",
    "scenario": "Exam Management - Additional validation test 3",
    "preconditions": "Exam Management module accessible",
    "steps": "Perform scenario 3 test in exam management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-084",
    "module": "Exam Management",
    "scenario": "Exam Management - Additional validation test 4",
    "preconditions": "Exam Management module accessible",
    "steps": "Perform scenario 4 test in exam management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-085",
    "module": "Exam Management",
    "scenario": "Exam Management - Additional validation test 5",
    "preconditions": "Exam Management module accessible",
    "steps": "Perform scenario 5 test in exam management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-086",
    "module": "Entrance Exam",
    "scenario": "Entrance Exam - Additional validation test 1",
    "preconditions": "Entrance Exam module accessible",
    "steps": "Perform scenario 1 test in entrance exam",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-087",
    "module": "Entrance Exam",
    "scenario": "Entrance Exam - Additional validation test 2",
    "preconditions": "Entrance Exam module accessible",
    "steps": "Perform scenario 2 test in entrance exam",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-088",
    "module": "Entrance Exam",
    "scenario": "Entrance Exam - Additional validation test 3",
    "preconditions": "Entrance Exam module accessible",
    "steps": "Perform scenario 3 test in entrance exam",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-089",
    "module": "Entrance Exam",
    "scenario": "Entrance Exam - Additional validation test 4",
    "preconditions": "Entrance Exam module accessible",
    "steps": "Perform scenario 4 test in entrance exam",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-090",
    "module": "Entrance Exam",
    "scenario": "Entrance Exam - Additional validation test 5",
    "preconditions": "Entrance Exam module accessible",
    "steps": "Perform scenario 5 test in entrance exam",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-091",
    "module": "Interviewer Management",
    "scenario": "Interviewer Management - Additional validation test 1",
    "preconditions": "Interviewer Management module accessible",
    "steps": "Perform scenario 1 test in interviewer management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-092",
    "module": "Interviewer Management",
    "scenario": "Interviewer Management - Additional validation test 2",
    "preconditions": "Interviewer Management module accessible",
    "steps": "Perform scenario 2 test in interviewer management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-093",
    "module": "Interviewer Management",
    "scenario": "Interviewer Management - Additional validation test 3",
    "preconditions": "Interviewer Management module accessible",
    "steps": "Perform scenario 3 test in interviewer management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-094",
    "module": "Interviewer Management",
    "scenario": "Interviewer Management - Additional validation test 4",
    "preconditions": "Interviewer Management module accessible",
    "steps": "Perform scenario 4 test in interviewer management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-095",
    "module": "Interviewer Management",
    "scenario": "Interviewer Management - Additional validation test 5",
    "preconditions": "Interviewer Management module accessible",
    "steps": "Perform scenario 5 test in interviewer management",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-096",
    "module": "Interview Evaluation",
    "scenario": "Interview Evaluation - Additional validation test 1",
    "preconditions": "Interview Evaluation module accessible",
    "steps": "Perform scenario 1 test in interview evaluation",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-097",
    "module": "Interview Evaluation",
    "scenario": "Interview Evaluation - Additional validation test 2",
    "preconditions": "Interview Evaluation module accessible",
    "steps": "Perform scenario 2 test in interview evaluation",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-098",
    "module": "Interview Evaluation",
    "scenario": "Interview Evaluation - Additional validation test 3",
    "preconditions": "Interview Evaluation module accessible",
    "steps": "Perform scenario 3 test in interview evaluation",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-099",
    "module": "Interview Evaluation",
    "scenario": "Interview Evaluation - Additional validation test 4",
    "preconditions": "Interview Evaluation module accessible",
    "steps": "Perform scenario 4 test in interview evaluation",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-100",
    "module": "Interview Evaluation",
    "scenario": "Interview Evaluation - Additional validation test 5",
    "preconditions": "Interview Evaluation module accessible",
    "steps": "Perform scenario 5 test in interview evaluation",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-101",
    "module": "Stanine Input",
    "scenario": "Stanine Input - Additional validation test 1",
    "preconditions": "Stanine Input module accessible",
    "steps": "Perform scenario 1 test in stanine input",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-102",
    "module": "Stanine Input",
    "scenario": "Stanine Input - Additional validation test 2",
    "preconditions": "Stanine Input module accessible",
    "steps": "Perform scenario 2 test in stanine input",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-103",
    "module": "Stanine Input",
    "scenario": "Stanine Input - Additional validation test 3",
    "preconditions": "Stanine Input module accessible",
    "steps": "Perform scenario 3 test in stanine input",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-104",
    "module": "Stanine Input",
    "scenario": "Stanine Input - Additional validation test 4",
    "preconditions": "Stanine Input module accessible",
    "steps": "Perform scenario 4 test in stanine input",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-105",
    "module": "Stanine Input",
    "scenario": "Stanine Input - Additional validation test 5",
    "preconditions": "Stanine Input module accessible",
    "steps": "Perform scenario 5 test in stanine input",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-106",
    "module": "Plus Factors",
    "scenario": "Plus Factors - Additional validation test 1",
    "preconditions": "Plus Factors module accessible",
    "steps": "Perform scenario 1 test in plus factors",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-107",
    "module": "Plus Factors",
    "scenario": "Plus Factors - Additional validation test 2",
    "preconditions": "Plus Factors module accessible",
    "steps": "Perform scenario 2 test in plus factors",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-108",
    "module": "Plus Factors",
    "scenario": "Plus Factors - Additional validation test 3",
    "preconditions": "Plus Factors module accessible",
    "steps": "Perform scenario 3 test in plus factors",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-109",
    "module": "Plus Factors",
    "scenario": "Plus Factors - Additional validation test 4",
    "preconditions": "Plus Factors module accessible",
    "steps": "Perform scenario 4 test in plus factors",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-110",
    "module": "Plus Factors",
    "scenario": "Plus Factors - Additional validation test 5",
    "preconditions": "Plus Factors module accessible",
    "steps": "Perform scenario 5 test in plus factors",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-111",
    "module": "Reporting",
    "scenario": "Reporting - Additional validation test 1",
    "preconditions": "Reporting module accessible",
    "steps": "Perform scenario 1 test in reporting",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-112",
    "module": "Reporting",
    "scenario": "Reporting - Additional validation test 2",
    "preconditions": "Reporting module accessible",
    "steps": "Perform scenario 2 test in reporting",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-113",
    "module": "Reporting",
    "scenario": "Reporting - Additional validation test 3",
    "preconditions": "Reporting module accessible",
    "steps": "Perform scenario 3 test in reporting",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-114",
    "module": "Reporting",
    "scenario": "Reporting - Additional validation test 4",
    "preconditions": "Reporting module accessible",
    "steps": "Perform scenario 4 test in reporting",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  },
  {
    "id": "TC-115",
    "module": "Reporting",
    "scenario": "Reporting - Additional validation test 5",
    "preconditions": "Reporting module accessible",
    "steps": "Perform scenario 5 test in reporting",
    "data": "Relevant form input data",
    "expected": "System functions correctly without unexpected behavior",
    "actual": "",
    "status": ""
  }
];

export default testCases;